# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=140)),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
